social/account/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import logout, login, logout_then_login, password_change, password_change_done, \
    password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .views import dashboard, register, edit

app_name = 'account'

urlpatterns = [
    # url(r'^login/$', views.user_login, name='login'),
    path('dashboard', dashboard, name='dashboard'),

    # LOGIN urls
    re_path('^login/$', login, name='login'),  # по дефолту ищет в registration/login.html
    path('logout', logout, name='logout'),
    path('logout-then-login', logout_then_login, name='logout_then_login'),

    # PASSWORD urls
    path('password-change/done', password_change_done, name='password_change_done'),
    path('password-change', password_change, name='password_change'),
    path('password-reset/done/', password_reset_done, name='password_reset_done'),
    path('password-reset/complete/', password_reset_complete, name='password_reset_complete'),
    path('password-reset/', password_reset, name='password_reset'),
    re_path('password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/', password_reset_confirm,
            name='password_reset_confirm'),

    # REGISTER urls
    path('register/', register, name='register'),

    # EDIT urls
    path('edit/', edit, name='edit'),
    re_path('^', dashboard, name='dashboard'),

]

social/account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete='CASCADE')
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y%m%d',  blank=True)
    objects = models.Manager()

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

social/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

social/account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib import messages


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)  # We set the user in the session by calling the login() method
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()  # to store the  data of the built-in User model
            profile_form.save()  # to store the additional profile data
            # messages.success(request, 'Profile updated ' 'successfully')
            return render(request, 'account/edit_done.html')
        else:
            messages.error(request, 'Something went wrong')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

social/account/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}Social{% endblock %}</title>
    {% block static %}
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script src="{% static 'js/scripts.js' %}" defer></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script><!-- для передачи токена в js запросах -->
    {% endblock %}

</head>
<body>
<div id="header">
    <span class="logo">Social</span>
    {% if request.user.is_authenticated %}
    <ul class="menu">
        <li class="{% if section == 'dashboard' %}selected{% endif %}"><a href="{% url 'account:dashboard' %}">My
            dashboard</a>
        </li>
        <li class=" {% if section == 'imges' %}selected{% endif %}"><a href="#">Images</a>
        </li>
        <li class=" {% if section == 'people' %}selected{% endif %}"><a href="#">People</a>
        </li>
    </ul>
    {% endif %}

    <span class="user">
         {% if request.user.is_authenticated %}
         Hello {{ request.user.first_name }},
         <a href="{% url 'account:logout' %}">Logout</a>
                {% else %}
        <a href="{% url 'account:login' %}">Login</a>
        {% endif %}
    </span>

</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">✖</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>
<!-- to include some specific js
<script>
 $(document).ready(function(){
 {% block domready %}
 {% endblock %}
 });
</script> -->