social/images/urls.py
from django.urls import path, re_path
from .views import image_create, image_detail, image_like


app_name = 'images'

urlpatterns = [
    path('create/', image_create, name='create'),
    re_path('detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', image_detail, name='detail'),
    path('like/', image_like, name='like'),
]

social/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    # one to many
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete='CASCADE')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y%m%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    # many to many
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    objects = models.Manager()


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

social/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput, }

    def clean_url(self):
        """
        Валидация расширения
        """
        url = self.cleaned_data['url']
        valid_extensions = ['jpeg', 'jpg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions: jpeg, jpg')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        # save=False, чтобы вызывать instance объекта, а не писать в БД
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = f'{slugify(image.title)}.{image_url.rsplit(".", 1)[1].lower()}'
        # download image from the given URL
        response = request.urlopen(image_url)
        # ContentFile чтобы сохранить в media
        image.image.save(image_name, ContentFile(response.read()),save=False)
        if commit:
            image.save()
        return image

social/images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from common.decorators import ajax_required


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # assign current user to the item
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', {'section': 'images',
                                                        'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request, 'images/image/detail.html', {'section': 'images', 'image': image})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    print(action, image_id, request.user)
    try:
        if image_id and action:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                print(image.users_like.all())
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
    except:
        print('exception')
    return JsonResponse({'status': 'ok'})

social/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
</form>
{% endblock %}

social/images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock %}
{% block content %}
<h1>{{ image.title }}</h1>
{% thumbnail image.image "300" as im %}
<a href="{{ image.image.url }}"><img src="{{ im.url }}" class="image-detail"></a>
{% endthumbnail %}

<!--tag to store the result of the QuerySet avoiding evaluating the same QuerySet twice-->
{% with total_likes=image.users_like.count users_like=image.users_like.all %}


<div class="image-info">
    <div>
                <span class="count">
                    <span id="total"> {{ total_likes }}</span> like{{ total_likes|pluralize }}
                </span>

        <!--------------- LIKE / UNLIKE --------------------->
        <a href="#" data-id="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}like"
           class="like button">
            {% if request.user not in users_like %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
        </a>
    </div>
    {{ image.description|linebreaks }}
</div>

<div class="image-likes">
    {% for user in image.users_like.all %}
    <div>
        <img src="{{ user.profile.photo.url }}">
        <p>user{{ user.first_name }}</p>
    </div>
    {% empty %}
    Nobody likes this image yet.
    {% endfor %}
</div>
{% endwith %}

<script>
$(document).ready(function(){

    var csrftoken = $.cookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
               xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });


    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
        {id: $(this).data('id'),
        action: $(this).data('action')},
        // CALLBACK FUNCTION (при ответе сервера)
        function(data){
            if (data['status'] == 'ok') {
                var previous_action = $('a.like').data('action');
                // toggle data-action
                $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                // toggle link text
                $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                // update total likes
                var previous_likes = parseInt($('#total').text());
                $('#total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
            }
        }
      );
    });
});
</script>
{% endblock %}