myshop/myshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import ProductSitemap
from shop.feeds import LatestProductsFeed

sitemaps = { 'products': ProductSitemap,}

urlpatterns = [
    re_path('^admin/', admin.site.urls),
    re_path('^sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path('^feed/$', LatestProductsFeed(), name='product_feed'),

    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path, re_path
from .views import *


app_name = 'shop'
urlpatterns = [
    re_path('^$', product_list, name='product_list'),
    re_path('^(?P<product_id>\d+)/share/$', product_share, name='product_share'),
    re_path('^tag/(?P<tag_slug>[-\w]+)/$',  product_list, name='product_list_by_tag'),
    re_path('^(?P<category_slug>[-\w]+)/$', product_list, name='product_list_by_category'),
    re_path('^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),
 ]

myshop/shop/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    # this is the slug for this product to build beautiful URLs.
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    objects = models.Manager()

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete='CASCADE')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)  # to build beautiful URLs.
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    # макс длина - 'max_digits' attribute, 'decimal_places' - число десятичных знаков
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    tags = TaggableManager()

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        # Both fields are indexed together to improve performances for queries that utilize the two fields

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class Comment(models.Model):
    product = models.ForeignKey(Product, related_name='comments', on_delete='CASCADE')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.product)

myshop/shop/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from .models import Category, Product, Comment
from taggit.models import Tag


def product_list(request, category_slug=None, tag_slug=None):
    category = None
    tag = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 2)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products,
                                                      'page': page,
                                                      'tag': tag
                                                      })


class ProductListView(ListView):
    queryset = Product.objects.all()
    context_object_name = 'products'
    paginate_by = 2
    template_name = 'shop/product/list.html'


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    comments = product.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar products
    product_tags_ids = product.tags.values_list('id', flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags_ids).exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count('tags')).order_by('-same_tags')[:4]
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'comments': comments,
                                                        'comment_form': comment_form,
                                                        'similar_products': similar_products})


def product_share(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            product_url = request.build_absolute_uri(product.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], product.name)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(product.name, product_url, cd['name'],
                                                                     cd['comments'])
            send_mail(subject, message, 'crowd.scoring@yandex.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'shop/product/share.html', {'product': product, 'form': form, 'sent': sent})

myshop/templates/shop/base.html
{% load shop_tags %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="ru">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta charset="utf-8">
<meta name="author" content="">
<title>Myshop </title>

<!-- Bootstrap 4 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
      integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/ec32966a69.js"></script>

<link href="{% static 'css/base.css' %}" rel="stylesheet">

<body>
<header>
    <a href="/" class="logo">My shop </a>

    <div id="subheader">
        <div class="cart"> Your cart is empty.</div>
    </div>
    {% total_products %} products are avaliable now!
    <p><a href="{% url 'product_feed' %}">Subscribe to my RSS feed</a></p>
</header>


<!--SIDEBAR ------>

<div class="sidebar">
    <div class="sub_side">
<div class="categories">
    <h4>Categories</h4>
            <ul class="col-md-12">
                    <li class="{% if not category %}selected{% endif %}"><a href="{% url 'shop:product_list' %}">All</a></li>
                    {% for c in categories %}
                        <li class="{% if category.slug == c.slug %}selected{% endif %}">
                            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
            </ul>
        </div>
    </div>
        <div class="sub_side">
        <div class="most_comment">
            <h4>Most commented products</h4>
            {% get_most_commented_products as mc_ps %}
            <ul class="col-md-12">
                {% for mc_p in mc_ps %}
                <li> <a href="{{ mc_p.get_absolute_url }}">{{ mc_p.name }}</a> </li>
                {% endfor %}
            </ul>
        </div>
    </div>
            <div class="sub_side">


        <div class="latest">
                {% latest_products 3 %}
        </div>
    </div>
</div>
<!--END SIDEBAR ------>

<div class="container">
    {% block content %}{% endblock %}
</div>


<div class="clearfix"></div>
{% block footer %}
<footer>
    <div class="col-xs-12 text-center">


        <a href="#" target="_blank"><i class="fa fa-github fa-2x" aria-hidden="true"> </i></a>
        <a href="mailto:crowd.scoring@yandex.ru"><i class="fa fa-envelope fa-2x" aria-hidden="true"> </i></a>
        <br>
        <strong> {% now "Y" as current_year %} Copyright &copy; viva-fidz, {{ current_year }}</strong>
    </div>
</footer>
{% endblock %}
</body>
</html>

myshop/templates/shop/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
             <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>
        {% if page.has_next %}
             <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load shop_tags %}

{% block title %}
    {% if category %}{{ category.title }}{% else %} Products {% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <div class="card-img ">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"  class="w-25 h-25">
            <h1>{{ product.name }}</h1>
            <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
            <p class="price">${{ product.price }}</p>
            <!--<p class="tags">Tags: {{ product.tags.all|join:", " }}</p>-->
            <p class="tags">Tags: {% for tag in product.tags.all %}
                <a href="{% url 'shop:product_list_by_tag' tag.slug %}"> {{ tag.name }} </a>
                 {% if not forloop.last %}, {% endif %}
                {% endfor %}</p>
        </div>
         <div class="card-body ">

            {{ product.description|markdown }}
        </div>
        <p><a href="{% url 'shop:product_share' product.id %}"> Share this product </a></p>


        {% with comments.count as total_comments %}
            {{ total_comments }} comment{{ total_comments|pluralize }}
        {% endwith %}
    </div>
    {% for comment in comments %}
     <div class="comment">
         <span class="author"><strong>{{ comment.name }}</strong></span>
         <span class="info"><em> {{ comment.created }}</em></span>
         {{ comment.body|linebreaks }}
     </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
         <h2>Add a new comment</h2>
         <form action="." method="post">
             {{ comment_form.as_p }}
             {% csrf_token %}
             <p><input type="submit" value="Add comment" class="btn-md btn-success"></p>
         </form>
    {% endif %}

        <h2>Similar_products:</h2>
        {% for p in similar_products %}
            <a href="{{ p.get_absolute_url }}"> {{ p.name }} </a>


        {% empty %}
             There are no similar products yet.
        {% endfor %}
{% endblock %}

myshop/templates/shop/product/latest_products.html
{% load static from staticfiles %}
    <h4>Last updates</h4>
    <ul class="col-md-12 text-left">
    {% for p in latest_products %}

          <li><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></li>

    {% endfor %}
    </ul>

myshop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load shop_tags %}

{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="row">

    <div id="main"  class="col-md-12">
        <h2>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h2>
        <div class="row">
            {% if tag %} <h4>products tagged with "{{ tag.name }}"</h4> {% endif %}
            {% for product in products %}
                <div class="m-2 p-2 card col-md-3 col-sm-5 col-xs-12 ">
                    <div class="card-body ">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static '/img/no_image.png' %}{% endif %}" class="w-25 h-25">
                        <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                        <p class="card-text">${{ product.price }}</p>

                    {% if product.tags.all %}
                        <p class="tags">Tags:
                            {% for tag in product.tags.all %}
                                <a href="{% url 'shop:product_list_by_tag' tag.slug %}"> {{ tag.name }} </a>
                                {% if not forloop.last %}, {% endif %}
                           {% endfor %}
                        </p>
                     {% endif %}
                        <!--<p class="card-text">{{ product.description|truncatewords:10|linebreaks }}</p>-->
                    </div>
                </div>
            {% endfor %}

        </div>
        <!--{% include "shop/pagination.html" with page=page_obj %}-->
        {% include "shop/pagination.html" with page=products %}

    </div>

</div>

{% endblock %}

myshop/templates/shop/product/share.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %} Product share {% endblock %}
{% block content %}
{% if sent %}
     <h1>E-mail successfully sent</h1>
     <p>
     "{{ product.name }}" was successfully sent to {{ cd.to }}.
     </p>
{% else %}
     <h1>Share "{{ product.name }}" by e-mail</h1>
     <form action="." method="post">
       {% for field in form %}
         <div>{{ field.label_tag }}</div>
     <div>
         {{ field.errors }}
         {{ field }} </div>
{% endfor %}
     <input type="submit" value="Send e-mail" class="btn-md btn-success">
            {% csrf_token %}

     </form>
{% endif %}
{% endblock %}